@url_dev=http://localhost:3000/api/v1/product
###
POST {{url_dev}}/create
x-api-key: 123456
x-client-id: 65b20267c702ae68e9f12c52
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWIyMDI2N2M3MDJhZTY4ZTlmMTJjNTIiLCJlbWFpbCI6InNob3BkZXYyMEBnbWFpbC5jb20iLCJpYXQiOjE3MDY2Njk4MTcsImV4cCI6MTcwNjg0MjYxN30.Bf9ucdUgG1PzAyvUAM3MZY7Ll-GsO7OPDx_VvTxZLtFxXYU_EyU8v3Mmm_7mZK8DukIks7aXz_VXarPV14GyfiZdBZFkwlTpED5buGRu69skNH_wIJk2PyMerrvLoAudBVAwsIt-jbkGR63bU5Ng7xg4jMRL_dc_1DbQwrDB3O2oug87cWfPCbMgb6FBsdQrwCIxCAAhROC2SQ8uF1OU66Jl5V-oKDLkaca5LW0tVBqPFKA949I4Qju-sgJbf2HCguBrwIKMOx-WGJjD7GRyDPgWCfHdO2LrZlsGMn--F-7qb1H-Cq8zexzUyDVA9brxfki5nYDWQCdZWpbJOUGRtO92LJhxvpNSbWD05T99WIFIIhWMSB-lnf-12ha9-0QGAeCkr4nGpMNcwhgmgJCXLPqB94TASi7l7KO8b4xNHywIN1yggpoILbbOVpiNWqdu0iOWQARKbkJqg05iyjHcJRldT0rSIMf_UdvLaeUn6RrOJ4VmC3qA-JvIwbImb-WxrdBOkTxkMTwAod4iKxC2coxwnofQjaWccP33iVZ6yFuEarFFguQ4xzN6KN6fy8K5JP9-kmt3F0Jw9A5_ntmxb0pZBf1bjIDFn3DOB8BbR1bRGdgJaEhhWfaUcJYL4eTFrxHqABjM5pj3vSD57H12Krc1K4SKZjvWx66f2G4_hPc
Content-Type: application/json
{
    "product_name": "product 4",
    "product_price": 1000,
    "product_description": "product 1 description",
    "product_thumbnail": "product 1 image",
    "product_quantity": 1,
    "product_type": "Electronics",
    "product_attributes": {
        "size": "S",
        "brand": "VM",
        "material": "Cotton"
    }
}

HTTP/1.1 200  - OK
content-security-policy: default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
origin-agent-cluster: ?1
referrer-policy: no-referrer
strict-transport-security: max-age=15552000; includeSubDomains
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-xss-protection: 0
content-type: application/json; charset=utf-8
content-length: 450
etag: W/"1c2-UK2a6IRKwtGUCEbdgj71mc4cHAg"
vary: Accept-Encoding
date: Wed, 31 Jan 2024 03:25:13 GMT
connection: close